[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "regex>=2025.11.3",
]

[tool.ruff]
src = ["tracking"]

[tool.ruff.lint]
extend-select = ["U", "TYP", "F", "I"]
